
document.querySelector('#img-selector').addEventListener('change', (element) => {
  // if (document.querySelector('#img-selector').value) {
  //     document.querySelector('.selected-image').innerHTML = `<img src="${document.querySelector('#img-selector').value}" alt="selected image" class="img-thumbnail">`;
  // } else {
  //     document.querySelector('#selected-image').innerHTML = '';
  // }

  const file = element.target.files[0];
  if (file) {
    // autogenerated code
    /* const reader = new FileReader();
    reader.onload = function(e) {
      document.querySelector('.selected-image').innerHTML = `<img src="${e.target.result}" alt="selected image" class="img-thumbnail">`;
    }
    reader.readAsDataURL(file); */
    let reader = new FileReader();
    reader.onload = (e) => {
      const image = document.createElement('img');
      image.src = e.target.result;
      image.alt = 'selected image';
      image.classList.add('img-thumbnail');
      const selectedImage = document.querySelector('#selected-image');
      selectedImage.innerHTML = '';
      selectedImage.appendChild(image);
      console.log(selectedImage);
    }
    reader.readAsDataURL(file);
  } else {
    document.querySelector('#selected-image').innerHTML = '';
  }
});